[Interface]
PrivateKey = $private_key
Address = ${client_ip}/24
DNS = $dns

[Peer]
PublicKey = $server_public_key
PresharedKey = $psk
Endpoint = $endpoint
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25