[General]
#this absolute path is used to generate the client config file
ABSALUTE_CLIENTS_FOLDER_PATH = /etc/wgau/
#path to the wireguard config file
WIREGUARD_CONFIG_FILE = /etc/wireguard/wg0.conf

[Wireguard]
#this is endpoint of your wireguard server
ENDPOINT = vpn.example.com:51820
#this is the base address for the client(from interface)
ADDRESS_BASE = 10.0.0
#this is the DNS server for the client
DNS_SERVER = 1.1.1.1

[Naming]
#this is the prefix for the client folder
CLIENT_PREFIX = client